import "../styles/globals.css";
import Head from "next/head";
import Layout from "./layout";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Palmer Doggie Depot</title>
        <meta
          name="Palmer Doggie Depot Website"
          content="Generated by create next app for Palmer Doggie Depot"
        />
      </Head>

      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default MyApp;
