import "../styles/globals.css";
import Head from "next/head";
import Layout from "./layout";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

function MyApp({ Component, pageProps }) {
  const [isLoaded, setIsLoaded] = useState(false);
  const router = useRouter();

  useEffect(() => {
    setIsLoaded(true);
    console.log("entered");
    return () => {
      console.log("Exited");
      setIsLoaded(false);
    };
  }, [router.pathname]);

  return (
    <>
      <Head>
        <title>Palmer Doggie Depot</title>
        <meta
          name="Palmer Doggie Depot Website"
          content="Generated by create next app for Palmer Doggie Depot"
        />
      </Head>

      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default MyApp;
